name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'SimpleApp/**'
      - 'helm/**'

env:
  RESOURCE_GROUP: your-resource-group-name
  AKS_CLUSTER_NAME: your-aks-cluster-name
  ACR_NAME: youracrname
  IMAGE_NAME: simple-dotnet-app
  IMAGE_TAG: latest
  HELM_RELEASE_NAME: simpleapp-release
  HELM_CHART_PATH: ./SimpleApp/helm/simpleapp

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./SimpleApp
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }} --admin --overwrite-existing

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ${{ env.HELM_CHART_PATH }} \
            --set deploy.registry=${{ env.ACR_NAME }}.azurecr.io \
            --set deploy.image=${{ env.IMAGE_NAME }} \
            --set deploy.tag=${{ env.IMAGE_TAG }}
